### PR TITLE
Permission Middleware Fix for Permitted Roles

### PR DESCRIPTION
**Pull request by prevosis**
Response to Issue #18. Fixed two bugs in the `findByID` functions. One error in `middleware.permission` would cause the `GET /user/{:id}` route to fail unless the requester was requesting their own user data. This fix opens it up to all admin / staff roles as well as the requester of their own data. In addition, a bug in `Model` caused all `findByID` calls to fail due to the use of an invalid attribute. 

Please let me know if I should make any changes here that would suit the project better.

### CODE REVIEW

**Comment by prevosis** [comment]
One thing I want to address is in `Model.findByID`, the use of `this.idAttribute`. I understand why this may be preferred (custom ID names I presume) but it doesn't seem like this would work here. Unless it's okay to assume that every model's `idAttribute` will be named `id`.

**Comment by nmagerko** [comment]
Looks good. The only thing that's really preventing me from merging this right now is that I had to refactor a lot of this middleware behavior in my feature branch (related to #5, see `feature/storage-integration`) so that we could properly handle raw request bodies. Nonetheless, the bug is still present there. Whatever we decide to do (merge this than fix the conflict or just use your fix in the feature branch), you'll get the credit for finding it and suggesting the fix.

I also see your fix for the `Model.findById` issue. Right idea -- the problem turns out to be that `this` is just strangely bound by Bookshelf's `extend` method, so `idAttribute` is recoverable (note that `idAttribute` is used by Bookshelf internally too). I have a fix for it in my branch that addresses the concern you talk about above (see [here](https://github.com/HackIllinois/api-2017/blob/feature/storage-integration/api/v1/models/Model.js#L24)).

**Comment by prevosis** [comment]
Awesome, thanks. I can take a look at your storage branch and see how to add the fixes in there given that it is more up-to-date, or if you'd like I can leave this alone for now and look into some other issues.

**Comment by nmagerko** [comment]
Fixed by #20

**Pull request closed without merging**
