### PR TITLE
JavaScript Linter

### PR DESCRIPTION
**Pull request by narendasan**
ok so I added the linter but 2 questions
1. what rules to do want to add to the linter?
2. do you want me to do the refactor for the linter in this branch or another?

### CODE REVIEW

**Comment by nmagerko** [comment]
1. I'm not sure. I'd say use your best judgement and add what you think is necessary
2. If you're willing to refactor what winds up needing to be changed, I'd say you can do it right in this branch. 

Now I see things that say "react" and "jsx" in there, which makes me wary because there are no front-end components in this repository. What's the reason for that? Other question I have is that there's an `import` plugin there, so were you planning to refactor everything into ES6/ES2016?

**Comment by nmagerko** [comment]
I'll re-enable Travis once we have this merged.

**Comment by narendasan** [comment]
So I used ESLint's config script to start the set of linter files. I believe these plugins might be dependencies of airbnb, but ill look into it a bit more

**Comment by tommypacker** [comment]
Can we close this at this point? I don't think we're gonna use this

**Comment by nmagerko** [comment]
Probably true. I'll close this and someone can re-open it if it's relevant.

**Pull request closed without merging**
