### PR TITLE
Better Configuration

### PR DESCRIPTION
**Pull request by narendasan**
So in trying to figure out how to run the api, I created a system to load them in on startup instead of in my .profile (since this is only used for this project that doesn't make any sense) 

A couple questions about this PR though:
1. Why are there redundant names for ENV variables
2. I want to make sure conventions make sense here ex. is having a startup script a good thing?

### CODE REVIEW

**Comment by nmagerko** [comment]
1. In redundant names I assume you're talking about why we have `LOCAL_MYSQL_X` and `RDS_X`? The RDS variables were to accommodate the AWS RDS env vars while the LOCAL env vars were just for devs. There is really no reason for anyone to set an RDS-prefixed variable. 
2. We should probably have that in the `package.json`. What you might do is add a `scripts` tag towards the end like `"scripts": { "dev" : "[whatever you wanna execute]" }`. That way we can have people run `npm dev` instead of running the start script directly.

Any ideas on where we could put the startup script instead of right in the root? If we take the `npm` approach, we can probably hide it in `resources/scripts` or something.

Regardless, I appreciate your refactoring this. Makes a lot more sense.

**Comment by narendasan** [comment]
So in the dev and prod scripts you could do a translation between the two, so its like a set once and forget and the system figures it out or might make sense to have a dev and prod config that way you could only set ```LOCAL*``` in dev and ```RDS*``` in prod

Resources makes sense as right now the only thing in there is the ascii art

**Comment by nmagerko** [comment]
Yeah separate scripts/set-up files might not be a bad idea. Just @ me when you want my review, and I'll add it.

**Comment by narendasan** [comment]
ok so everything that needs to function has been written so you can review that @nmagerko. The one question I have is do we want to continue to have the line about adding to the .bash_profile for env variables still?

**Comment by nmagerko** [comment]
@narendasan We can probably get rid of that line given that we have the configs now. I do wonder if it makes sense to still have the RDS and LOCAL database configuration keys, though. 

Just from a quick look at your setup script, it looks like I could just set something like `DB_NAME = $RDS_DB_NAME` and the bash script would correctly set the variable from the environment. Perhaps we should scrap the prefixes to those variables and just look for `DB_NAME`, `DB_HOST`, etc from the API.

**Comment by narendasan** [comment]
yeah I would agree about dropping the prefix. is RDS_DB used for anything else on the aws side?

**Comment by nmagerko** [comment]
Not that I can tell. It's supplied by the AWS environment anyhow, so if it's needed, it'll be around.

**Comment by narendasan** [comment]
ok @nmagerko dropped the prefixing

**Comment by nmagerko** [comment]
@narendasan were you planning to make any changes to the application configuration? I would assume that the configuration is probably malfunctioning since the names of some of the keys are different now.

I can make that change and then review if you want.

**Comment by narendasan** [comment]
@nmagerko go ahead and make the change

**Comment by narendasan** [comment]
So I added a system that doesn't allow template values to be deployed in production. I wasn't sure how to deal with db defaults, my instinct was to leave them in the config file as long as we change the db name later, just because most people won't change that too much from the default values, but I will leave that up to you.

**Comment by narendasan** [comment]
@nmagerko before this gets merged can you look at config.js and see if what I am leaving in there makes sense?

**Comment by nmagerko** [comment]
@narendasan for sure. I'll go through it all tonight or tomorrow

**Comment by nmagerko** [comment]
Changed a couple of defaults and modified the way empty values are handled a bit. I think we're in good shape now. I'll merge this tonight.

**Pull request merged**
