### PR TITLE
Permission Middleware & Package Fixes

### PR DESCRIPTION
**Pull request by prevosis**
1. Added `aws-sdk` module to package.json, API would fail on initial `node api.js` call otherwise
2. Added fix from #19 into the more up-to-date middleware on this branch

Please let me know if there are any changes I should make.

### CODE REVIEW

**Comment by nmagerko** [comment]
Maybe we just need to re-order this middleware's checks. I see multiple `!_.includes(allowed, req.auth.role)`, which probably means the order I had it in is not fitting. 

Maybe it would be better if we did something like:
- `req.auth` is null => error
-  `_.includes(allowed, req.auth.role)` => continue
- `isOwner` defined, do existing checks => continue | error

Feel free to play around with that so that it works/looks the way you want. Please update the comments as necessary.

**Comment by nmagerko** [comment]
I'll be making a PR for this feature, but I'll hold off on any merges until this is ready.

**Comment by prevosis** [comment]
Sounds good. I'm out of town and won't be able to work on this for a week or so, but once I get back I'll be able to make the necessary changes.

**Comment by prevosis** [comment]
Made the necessary fixes. Please let me know if there is anything that needs to be done here.

**Comment by nmagerko** [comment]
Looks nice. We usually have two code reviewers, but I think it'll suffice to have just one for this PR. If you can confirm you've tested this, I'll merge it.

**Comment by prevosis** [comment]
Confirmed.

**Comment by nmagerko** [comment]
Great. Then this will take the place of #19

**Pull request merged**
