### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by prevosis**
Response to #23. Adding some basic testing for the present functionality. Currently I have only worked on user functionality but we can add the other services (depending on how easy they are to simulate/mock, as Nick pointed out in #23). I think following the format I have would be effective in separating the different types of tests, although I am open to any suggestions here. Below I have outlined the tests that are present and those that need to be done. 

I am currently making this PR to merge into the source repo testing branch. This is because a lot of the testing works because of fixes in `storage-integration` which aren't present in `staging`. Once `storage-integration` is merged into `staging`, we can probably merge this branch as well. Again, open to suggestions here about this process. 
- [x] Add tests for general user functionality
  - [x] Accessing own user via ID
  - [x] Not being able to access other users via their IDs
  - [x] Not being able to create roled users
  - [x] Resetting password
- [x] Add tests for staff user functionality
  - [x] Being able to create roled users
  - [x] Being able to access every user via their ID
- [x] Add tests for authentication endpoints
- [ ] Add tests for storage
  - [ ] Uploading resume
  - [ ] Accessing resume via ID
  - [ ] Changing resume
- [ ] Add tests for mail service

The tests I have currently added are likely not enough as they are. More complicated integration tests would be useful here. 

Also, the larger amount of commits / file changes is because I have been using `storage-integration` as the base branch for this branch, which hasn't been merged in yet.

### CODE REVIEW

**Comment by nmagerko** [comment]
Woah sorry just saw this. But very nice! I'll look over this as soon as I can.

**Comment by nmagerko** [comment]
One quick question: does this have storage stuff in it? If so, we'll need one more code review on that feature done before we can merge this in (you could be the second code reviewer!). See #21

**Comment by prevosis** [comment]
Yes I made the testing branch from the storage-integration branch. I'd be happy to check it out.

**Comment by nmagerko** [comment]
This PR has deviated a lot since it was originally created. Let's create a new one to more accurately describe what's new.

**Pull request closed without merging**
